### ISSUE TITLE
DTO Generator Command

### ISSUE THREAD

**Issue by jordanpartridge** [jordanpartridge/claude-tools#1]
Create an artisan command for generating DTOs from JSON/YAML schemas

Features needed:
- Generate DTOs from schema definition
- Support for nested objects
- Support for collections
- Generate corresponding tests
- Support for validation rules
- Support for custom casts
- Support for relationships

Example usage:
```bash
php artisan claude:make:dto User --schema=user-schema.json
php artisan claude:make:dto-suite --schema=api-schema.yaml
```

Schema format example:
```yaml
User:
  fields:
    id: integer
    name: string
    email: string|email
    posts: HasMany<Post>
    profile: HasOne<Profile>
  validation:
    name: required|max:255
    email: required|email|unique:users
```
